### ISSUE TITLE
Encryption not working

### ISSUE THREAD

**Issue by gad3r** [Hamza-Megahed/hg532#4]
Don't work:
Traceback (most recent call last):
  File "./hg532_config.py", line 169, in <module>
    main()
  File "./hg532_config.py", line 160, in main
    encrypt_config(input_file, output_file)
  File "./hg532_config.py", line 118, in encrypt_config
    check_config(new_config_file)
NameError: global name 'check_config' is not defined

**Comment by jututt** [comment]
add comment at the beginning of line 118
`# check_config(new_config_file)`
